# Generated by Django 3.0.5 on 2020-05-07 02:48

from django.db import migrations, models
import django.db.models.deletion
import match.helpers.date_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_index=True)),
                ('access_code', models.CharField(db_index=True, max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('sets_number', models.IntegerField()),
                ('game_status', models.IntegerField()),
                ('set_points_number', models.IntegerField()),
                ('points_difference', models.IntegerField()),
                ('tie_break_points', models.IntegerField()),
                ('changed', models.DateTimeField(default=match.helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=match.helpers.date_helpers.get_current_utc_datetime)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
                ('changed', models.DateTimeField(default=match.helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=match.helpers.date_helpers.get_current_utc_datetime)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status', models.IntegerField(db_index=True)),
                ('team_one_points', models.IntegerField()),
                ('team_two_points', models.IntegerField()),
                ('set_number', models.IntegerField()),
                ('is_tie_break', models.BooleanField(default=False)),
                ('changed', models.DateTimeField(default=match.helpers.date_helpers.get_current_utc_datetime)),
                ('created', models.DateTimeField(default=match.helpers.date_helpers.get_current_utc_datetime)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.Match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(to='match.Team'),
        ),
    ]
